/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProjektiRouteImport } from './routes/projekti'
import { Route as OMeniRouteImport } from './routes/o-meni'
import { Route as NagradeRouteImport } from './routes/nagrade'
import { Route as KontaktRouteImport } from './routes/kontakt'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProjektiSlugRouteImport } from './routes/projekti.$slug'

const ProjektiRoute = ProjektiRouteImport.update({
  id: '/projekti',
  path: '/projekti',
  getParentRoute: () => rootRouteImport,
} as any)
const OMeniRoute = OMeniRouteImport.update({
  id: '/o-meni',
  path: '/o-meni',
  getParentRoute: () => rootRouteImport,
} as any)
const NagradeRoute = NagradeRouteImport.update({
  id: '/nagrade',
  path: '/nagrade',
  getParentRoute: () => rootRouteImport,
} as any)
const KontaktRoute = KontaktRouteImport.update({
  id: '/kontakt',
  path: '/kontakt',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjektiSlugRoute = ProjektiSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => ProjektiRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/kontakt': typeof KontaktRoute
  '/nagrade': typeof NagradeRoute
  '/o-meni': typeof OMeniRoute
  '/projekti': typeof ProjektiRouteWithChildren
  '/projekti/$slug': typeof ProjektiSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/kontakt': typeof KontaktRoute
  '/nagrade': typeof NagradeRoute
  '/o-meni': typeof OMeniRoute
  '/projekti': typeof ProjektiRouteWithChildren
  '/projekti/$slug': typeof ProjektiSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/kontakt': typeof KontaktRoute
  '/nagrade': typeof NagradeRoute
  '/o-meni': typeof OMeniRoute
  '/projekti': typeof ProjektiRouteWithChildren
  '/projekti/$slug': typeof ProjektiSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/kontakt'
    | '/nagrade'
    | '/o-meni'
    | '/projekti'
    | '/projekti/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/kontakt'
    | '/nagrade'
    | '/o-meni'
    | '/projekti'
    | '/projekti/$slug'
  id:
    | '__root__'
    | '/'
    | '/kontakt'
    | '/nagrade'
    | '/o-meni'
    | '/projekti'
    | '/projekti/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  KontaktRoute: typeof KontaktRoute
  NagradeRoute: typeof NagradeRoute
  OMeniRoute: typeof OMeniRoute
  ProjektiRoute: typeof ProjektiRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/projekti': {
      id: '/projekti'
      path: '/projekti'
      fullPath: '/projekti'
      preLoaderRoute: typeof ProjektiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/o-meni': {
      id: '/o-meni'
      path: '/o-meni'
      fullPath: '/o-meni'
      preLoaderRoute: typeof OMeniRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nagrade': {
      id: '/nagrade'
      path: '/nagrade'
      fullPath: '/nagrade'
      preLoaderRoute: typeof NagradeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kontakt': {
      id: '/kontakt'
      path: '/kontakt'
      fullPath: '/kontakt'
      preLoaderRoute: typeof KontaktRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projekti/$slug': {
      id: '/projekti/$slug'
      path: '/$slug'
      fullPath: '/projekti/$slug'
      preLoaderRoute: typeof ProjektiSlugRouteImport
      parentRoute: typeof ProjektiRoute
    }
  }
}

interface ProjektiRouteChildren {
  ProjektiSlugRoute: typeof ProjektiSlugRoute
}

const ProjektiRouteChildren: ProjektiRouteChildren = {
  ProjektiSlugRoute: ProjektiSlugRoute,
}

const ProjektiRouteWithChildren = ProjektiRoute._addFileChildren(
  ProjektiRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  KontaktRoute: KontaktRoute,
  NagradeRoute: NagradeRoute,
  OMeniRoute: OMeniRoute,
  ProjektiRoute: ProjektiRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
